services:
  db:
    container_name: db
    networks:
      - ratbot
    ports:
      - 127.0.0.1:3306:3306/tcp
    volumes:
      - ./data:/var/lib/mysql
    env_file: .db.env
    environment:
      - TZ=America/Chicago
    restart: on-failure
    image: mariadb:10.3
    #image: mysql:8

  ratbot:
    container_name: ratbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RATBOT_SRC_COMMIT: 78ba53e
    networks:
      - ratbot
    volumes:
      - /var/log/ratbot.log:/var/log/ratbot.log
    env_file: .env
    environment:
      - TZ=America/Chicago
    depends_on:
      - mariadb
    restart: on-failure
    image: ratbot:78ba53e

networks:
  ratbot:
    external: true
