services:
  mariadb:
    container_name: mariadb
    #container_name: mysql
    depends_on:
      - ratbot
    networks:
      - ratbot
    ports:
      - 127.0.0.1:3306:3306/tcp
    volumes:
      - ./db_data:/var/lib/mysql
    env_file: .mysql.env
    environment:
      - TZ=America/Chicago
    restart: on-failure
    image: mariadb:10.3
    #image: mysql:8

  ratbot:
    container_name: ratbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RATBOT_SRC_COMMIT: af2183b
    networks:
      - ratbot
    volumes:
      - /var/log/ratbot.log:/var/log/ratbot.log
    env_file: .env
    environment:
      - TZ=America/Chicago
    restart: on-failure
    image: ratbot:af2183b

volumes:
  db_data:
    driver: local

networks:
  ratbot:
    external: true
